-- ============================================
-- TABLE: GESTION DES SIÈGES D'AVION
-- ============================================

-- Table: siege
-- Représente les sièges physiques disponibles dans chaque avion
CREATE TABLE IF NOT EXISTS siege (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_avion INTEGER NOT NULL,
    numero_siege VARCHAR(10) NOT NULL,
    classe VARCHAR(50) NOT NULL,
    disponible BOOLEAN DEFAULT TRUE,
    date_creation TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    date_modification TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_siege_avion FOREIGN KEY (id_avion) 
        REFERENCES avion(id),
    CONSTRAINT unique_siege_avion UNIQUE (id_avion, numero_siege)
);

-- Table: reservation_siege
-- Associe les sièges aux billets/réservations
CREATE TABLE IF NOT EXISTS reservation_siege (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_billet BIGINT NOT NULL,
    id_siege BIGINT NOT NULL,
    id_vol_fille INTEGER NOT NULL,
    date_reservation TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reservation_siege_billet FOREIGN KEY (id_billet) 
        REFERENCES billet(id),
    CONSTRAINT fk_reservation_siege_siege FOREIGN KEY (id_siege) 
        REFERENCES siege(id),
    CONSTRAINT fk_reservation_siege_vol FOREIGN KEY (id_vol_fille) 
        REFERENCES vol_fille(id),
    CONSTRAINT unique_siege_reservation UNIQUE (id_siege, id_vol_fille)
);

-- Index pour optimiser les requêtes
CREATE INDEX idx_siege_avion ON siege(id_avion);
CREATE INDEX idx_siege_classe ON siege(classe);
CREATE INDEX idx_siege_disponible ON siege(disponible);
CREATE INDEX idx_reservation_siege_billet ON reservation_siege(id_billet);
CREATE INDEX idx_reservation_siege_vol ON reservation_siege(id_vol_fille);

-- ============================================
-- INSERTION DES SIÈGES POUR CHAQUE AVION
-- ============================================

-- Avion 1 (5R-MFT - Boeing 737-800, capacité 189)
-- Configuration: 12 Affaires + 177 Économique
DO $$
BEGIN
    -- Sièges Affaires (1A-6F)
    FOR i IN 1..6 LOOP
        INSERT INTO siege (id_avion, numero_siege, classe, disponible)
        VALUES (1, i || 'A', 'Affaires', TRUE);
        INSERT INTO siege (id_avion, numero_siege, classe, disponible)
        VALUES (1, i || 'B', 'Affaires', TRUE);
    END LOOP;
    
    -- Sièges Économique (7A-32F)
    FOR row_num IN 7..32 LOOP
        FOR col IN 'A'::text..'F'::text LOOP
            INSERT INTO siege (id_avion, numero_siege, classe, disponible)
            VALUES (1, row_num || col, 'Economique', TRUE);
        END LOOP;
    END LOOP;
END $$;

-- Avion 2 (5R-MGA - Airbus A320, capacité 180)
-- Configuration: 12 Affaires + 168 Économique
DO $$
BEGIN
    -- Sièges Affaires (1A-6B)
    FOR i IN 1..6 LOOP
        INSERT INTO siege (id_avion, numero_siege, classe, disponible)
        VALUES (2, i || 'A', 'Affaires', TRUE);
        INSERT INTO siege (id_avion, numero_siege, classe, disponible)
        VALUES (2, i || 'B', 'Affaires', TRUE);
    END LOOP;
    
    -- Sièges Économique (7A-32F)
    FOR row_num IN 7..32 LOOP
        FOR col IN 'A'::text..'F'::text LOOP
            INSERT INTO siege (id_avion, numero_siege, classe, disponible)
            VALUES (2, row_num || col, 'Economique', TRUE);
        END LOOP;
    END LOOP;
END $$;

-- Avion 3 (5R-MGB - ATR 72-600, capacité 72)
-- Configuration: 72 Économique
DO $$
BEGIN
    FOR row_num IN 1..12 LOOP
        FOR col IN 'A'::text..'F'::text LOOP
            INSERT INTO siege (id_avion, numero_siege, classe, disponible)
            VALUES (3, row_num || col, 'Economique', TRUE);
        END LOOP;
    END LOOP;
END $$;

-- Avion 4 (5R-MGC - Embraer E190, capacité 100)
-- Configuration: 100 Économique
DO $$
BEGIN
    FOR row_num IN 1..17 LOOP
        FOR col IN 'A'::text..'F'::text LOOP
            IF (row_num * 6 - (6 - (col::text = 'A')::int - (col::text = 'B')::int - (col::text = 'C')::int - 
                               (col::text = 'D')::int - (col::text = 'E')::int - (col::text = 'F')::int)) <= 100 THEN
                INSERT INTO siege (id_avion, numero_siege, classe, disponible)
                VALUES (4, row_num || col, 'Economique', TRUE);
            END IF;
        END LOOP;
    END LOOP;
END $$;

-- Vérification
SELECT 'Sièges créés avec succès' AS status;
SELECT id_avion, classe, COUNT(*) as nombre FROM siege GROUP BY id_avion, classe ORDER BY id_avion, classe;
